<Category>:
    name: "category"
    on_enter:
        self.update_rv_data(rv1)
    BoxLayout:
        orientation: "vertical"
        TopInfo:
        MDTabs:
            background_color: get_color_from_hex("#FAFAFA")
            text_color_normal: get_color_from_hex("#A5D6A7")
            text_color_active: app.theme_cls.primary_color
            indicator_color: app.theme_cls.primary_color
            fixed_tab_label_width: Window.width/5 if platform != "android" else self.fixed_tab_label_width
            allow_stretch: False
            lock_swiping: False
            on_tab_switch:
                root.update_rv_data(args[1].children[0])
            Tab:
                title: icon("icecream", size=24 if platform != "android" else 40)
                name: "snacks"
                RV:
                    id: rv1
            Tab:
                title: icon("grass", size=24 if platform != "android" else 40)
                name: "vegetables"
                RV:
                    id: rv2
            Tab:
                title: icon("ramen_dining", size=24 if platform != "android" else 40)
                name: "food"
                RV:
                    id: rv3
            Tab:
                title: icon("liquor", size=24 if platform != "android" else 40)
                name: "drinks"
                RV:
                    id: rv4
            Tab:
                title: icon("architecture", size=24 if platform != "android" else 40)
                name: "materials"
                RV:
                    id: rv5