<Category>:
    name: "category"
    on_enter:
        self.update_rv_data(rv1)
    BoxLayout:
        orientation: "vertical"
        TopInfo:
        ScrollView:
            id: sv
            size_hint_y: None
            height: marker.height
            do_scroll_y: False
            effect_cls: _ScrollViewHardStop
            bar_width: 0
            MDBoxLayout:
                id: marker
                adaptive_size: True
                padding: dp(10)
                spacing: dp(20)
                TabBar:
                    text: f"{icon('icecream')} Snacks"
                    root: root
                    text_color: 1, 1, 1, 1
                    md_bg_color: app.theme_cls.primary_color
                TabBar:
                    text: f"{icon('grass')} Vegetables"
                    root: root
                TabBar:
                    text: f"{icon('ramen_dining')} Foods"
                    root: root
                TabBar:
                    text: f"{icon('liquor')} Drinks"
                    root: root
                TabBar:
                    text: f"{icon('architecture')} Materials"
                    root: root
        ScreenManager:
            id: manager
            transition: CardTransition(direction="up")
            Screen:
                name: "snacks"
                RV:
                    id: rv1
            Screen:
                name: "vegetables"
                on_enter: root.update_rv_data(rv2)
                RV:
                    id: rv2
            Screen:
                name: "foods"
                on_enter: root.update_rv_data(rv3)
                RV:
                    id: rv3
            Screen:
                name: "drinks"
                on_enter: root.update_rv_data(rv4)
                RV:
                    id: rv4
            Screen:
                name: "materials"
                on_enter: root.update_rv_data(rv5)
                RV:
                    id: rv5
