<Home>:
    name: "home"
    BoxLayout:
        orientation: "vertical"
        MDBoxLayout:
            adaptive_height: True
            padding: dp(10)
            M_CardTextField:
                elevation: 10
                hint_text: "search"
                icon_right: icon("search")
                radius: dp(20)
                text_field_disabled: True
                icon_right_color: app.theme_cls.primary_color
                icon_left_color: app.theme_cls.primary_color
                foreground_color: [0, 0, 0, 0.8] if app.theme_cls.theme_style == "Light" else [1,1,1,1]
                cursor_color: [0, 0, 0, .7] if app.theme_cls.theme_style == "Light" else [1,1,1,1]
                md_bg_color: [1,1,1,1] if app.theme_cls.theme_style == "Light" else get_color_from_hex("1f1f1f")
                background_color: [1,1,1,1] if app.theme_cls.theme_style == "Light" else get_color_from_hex("1f1f1f")
                disabled_foreground_color: [0.5, 0.5, 0.5, 1.0]
        RecycleView:
            id: rv
            effect_cls: ScrollEffect
            key_viewclass: "viewclass"
            do_scroll_x: True
            data:[{"viewclass": "TopInfo"}, {"viewclass": "CarouselLayout"}, {"viewclass": "CarouselLayout"}, {"viewclass": "CarouselLayout"}, {"viewclass": "CarouselLayout"}]
            RecycleGridLayout:
                id: holder
                root: root.manager
                roots: root
                default_size_hint: 1, None
                default_size: None, None
                size_hint_y: None
                height: self.minimum_height
                spacing:dp(5)
                cols: 1
                key_size: "height"



