<Home>:
    name: "home"
    BoxLayout:
        orientation: "vertical"
        TopInfo:
            id: top_info

        CarouselLayout:
            id: swipe
        RecycleView:
            id: rv
            data: [{"source": f"{image_path}shoes.jpg"}, {"source": f"{image_path}shoes.jpg"}, {"source": f"{image_path}shoes.jpg"}, {"source": f"{image_path}shoes.jpg"}]
            effect_cls: _ScrollViewHardStop
            viewclass: "Products"
            do_scroll_x: True
            do_scroll_y: False
            RecycleBoxLayout:
                id: holder
                root: root.manager
                roots: root
                default_size_hint: None, 1
                default_size: None, None
                size_hint_x: None
                width: self.minimum_width
                spacing:dp(10)
                padding: dp(10)
                orientation: "horizontal"
                key_size: "width"
        AKBottomNavigation2:
            id: nav
            NavButton:
                id: home
                text: "home"
                on_kv_post:
                    self.ids._icon.markup = True
                    self.ids._icon.text = icon("home")
            NavButton:
                id: cat
                text: "category"
                on_kv_post:
                    self.ids._icon.markup = True
                    self.ids._icon.text = icon("category")
            NavButton:
                id: settings
                text: "settings"
                on_kv_post:
                    self.ids._icon.markup = True
                    self.ids._icon.text = icon("settings")




