<TextInput>:
    on_focus: app.on_focus(args[1])
<MDTextField>:
    on_focus: app.on_focus(args[1])
<MDLabel>:
    theme_text_color: "Custom"
    color: get_color_from_hex("#263238")
<ProfilePix@ButtonBehavior+Widget>:
    size_hint: None, None
    size: dp(60), dp(60)
    source: ""
    on_release:
        print("hello")
    canvas.before:
        Color:
            rgba: 1,1,1,1
        Ellipse:
            size: self.size
            pos: self.pos
            source: self.source

<CardButton@MDCard>:
    size_hint_y: None
    height:dp(45)
    text: ""
    ripple_behavior: True
    radius: [dp(10)]
    MDLabel:
        text: root.text
        halign: "center"
        font_style: "Button"
        theme_text_color: "Custom"
        text_color: 1,1,1,1

<Swiper@MDBoxLayout>:
    padding: dp(10)
    orientation: "vertical"
    spacing: dp(10)
    MDBoxLayout:
        adaptive_height: True
        MDLabel:
            text: "Man Shoes"
            font_style: "H5"
            size_hint_y: None
            height: self.texture_size[1]
        MDCard:
            size_hint: None, None
            size: self.minimum_size
            radius: [dp(30)]
            elevation: 0.2
            MDIconButton:
                icon: "heart-outline"
                theme_text_color: "Custom"
                text_color: get_color_from_hex("FF1744")
    MDBoxLayout:
        RelativeLayout:
            MDCard:
                elevation: 10
                radius: [dp(10)]
                size_hint_x: None
                width: Window.width/2.3
                pos_hint: {"center_x": .5}
                RoundedImage:
                    source: f"{image_path}shoes.jpg"
                    radius: [dp(10)]
        MoneyLabel:
            text: f"[font=Roboto]₦[/font]200,000.00"
            halign: "center"
            size_hint_x:.7
    MDBoxLayout:
        adaptive_height: True
        spacing: dp(10)
        CardButton:
            text: "Buy Now"
            md_bg_color: app.theme_cls.primary_color
            radius: [dp(7), dp(20), dp(7), dp(20)]
            on_release: app.root.current = "lookout"
        CardButton:
            md_bg_color: get_color_from_hex("00B8D4")
            radius: [dp(7), dp(20), dp(7), dp(20)]
            text: "Add To Cart"

        CardButton:
            md_bg_color: get_color_from_hex("6200EA")
            radius: [dp(7), dp(20), dp(7), dp(20)]
            text: "View Product"

<CarouselLayout>
    adaptive_height: True
    orientation: "vertical"
    swipers: []
    Carousel:
        size_hint_y: None
        height: Window.height/2.5
        pagnitors:[_0, _1, _2, _3]
        on_index:
            root.swipe_pagnitors(*args)
        Swiper:
            id: s0
        Swiper:
            id: s1
        Swiper:
            id: s2
        Swiper:
            id: s3
    RelativeLayout:
        size_hint_y:None
        height: dp(10)
        MDBoxLayout:
            adaptive_size: True
            spacing: dp(10)
            pos_hint: {"center_x": .5}
#            MDIconButton:
#                on_text:
#                    self.lbl_txt.markup = True
#                    self.lbl_txt.text = icon("chevron_left")
            ItemPagination
                id: _0
            ItemPagination:
                id: _1
                current_index: 1
            ItemPagination:
                id: _2
                current_index: 2
            ItemPagination:
                id: _3
                current_index: 3
#            MDIconButton:
#                on_text:
#                    self.lbl_txt.markup = True
#                    self.lbl_txt.text = icon("chevron_right")

<TopInfo@MDBoxLayout>:
    adaptive_height: True
    padding: [dp(15), dp(5), dp(15), dp(5)]
    icon_left: icon("menu")
    icon_right: icon("search")
    extra_icons_right: {"cart": ["custom", icon("shopping_basket")], "profile": ["source", image_path +"p.png"]}
    extra_icons_right_color: {"cart": app.theme_cls.primary_color}
    icon_right_color: app.theme_cls.primary_color
    icon_left_color: app.theme_cls.primary_color
    text_field_disabled: False
    icon_left_callback: lambda x: None
    extra_icons_right_callback:{}
    M_CardTextField:
        elevation: 10
        hint_text: "Search"
        icon_left: root.icon_left
        icon_right: root.icon_right
        icon_left_callback: root.icon_left_callback
        font_name: f"{font_path}DINAlternate-bold.ttf"
        extra_icons_right: root.extra_icons_right
        extra_icons_right_color: root.extra_icons_right_color
        extra_icons_right_callback: root.extra_icons_right_callback
        radius: [dp(10)]
        text_field_disabled: root.text_field_disabled
        icon_right_color: root.icon_right_color
        icon_left_color: root.icon_left_color
        foreground_color: [0, 0, 0, 0.8] if app.theme_cls.theme_style == "Light" else [1,1,1,1]
        cursor_color: [0, 0, 0, .7] if app.theme_cls.theme_style == "Light" else [1,1,1,1]
        md_bg_color: [1,1,1,1] if app.theme_cls.theme_style == "Light" else get_color_from_hex("1f1f1f")
        background_color: [1,1,1,1] if app.theme_cls.theme_style == "Light" else get_color_from_hex("1f1f1f")
        disabled_foreground_color: [0.5, 0.5, 0.5, 1.0]

<ItemPagination>
    size_hint: None, None
    size: dp(20), dp(4)
    pos_hint: {'center_y': .5}

    canvas:
        Color:
            rgba:
                self.theme_cls.primary_color\
                if root.current_index == 0 else root.color_round_not_active
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(2)]

<NavButton@Button_Item>:
    icon_color: 1,1,1,1
    text_color: 1,1,1,1
    button_bg_color: app.theme_cls.primary_color
    badge_disabled: True

<BoxButton@ButtonBehavior+MDBoxLayout>

<Products@MDCard>:
    orientation: "vertical"
    radius: [dp(10)]
    size_hint_x: None
    _size: 0, 0
    size: self._size
    source: ""
    spacing: dp(2)
    on_kv_post:
        Animation(opacity=1, d=1, t="out_quad").start(self)

    BoxButton:
        orientation: "vertical"
        on_release: print("hello")
        RoundedImage:
            id: image
            radius: [root.radius[0], root.radius[0], 0, 0]
            source: root.source

        MDBoxLayout:
            adaptive_height: True
            orientation: "vertical"
            padding: [dp(10), 0, dp(10), 0]
            MDLabel:
                text: "Onye Owa Shoes"
                size_hint_y: None
                font_style: "H6"
                height: self.texture_size[1]
                markup: True
    MDBoxLayout:
        adaptive_height: True
        padding: [dp(10), 0, dp(10), 0]
        spacing: dp(5)
        MoneyLabel:
            text:f"[font=Roboto]₦[/font]20,000.00"
            size_hint_y: None
            height: self.texture_size[1]
            pos_hint:{"center_y": .5}
        MDIconButton:
            icon: "heart-outline"
            theme_text_color: "Custom"
            text_color: get_color_from_hex("FF1744")
    MDBoxLayout:
        adaptive_height: True
        padding: [dp(10), 0, dp(10), dp(5)]
        CardButton:
            id: bt
            md_bg_color: app.theme_cls.primary_color
            text: "Add To Cart"
            radius: [dp(20)]
            on_release: print("hello", args)

<NocenStore@MDBoxLayout>:
    adaptive_height: True
    size_hint_x: None
    width: Window.width/3
    md_bg_color: 0,1,0,.1
    pos_hint:{"center_y": .5}
    radius: [dp(5)]
    MDLabel:
        id: la
        text: "NOCENSTORE"
        italic: True
        color: app.theme_cls.primary_color
        size_hint_y: None
        font_style: "Caption"
        height: self.texture_size[1]
        halign: "center"

<RoundedImage@AsyncImage>:
    radius: [dp(5)]
    anim_delay: .1
    canvas.before:
        StencilPush:
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: self.radius if self.radius else [dp(5)]
        StencilUse
    canvas.after:
        StencilUnUse:
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: self.radius if self.radius else [dp(5)]
        StencilPop
<MoneyLabel@MDLabel>:
    text:f""
    font_style: "H6"
    markup: True
    pos_hint:{"center_y": .5}
    theme_text_color: "Custom"
    text_color: app.theme_cls.primary_color

<ProductLandscape@MDCard>:
    orientation: "horizontal"
    size_hint_y: None
    _size: 0, 0
    size: self._size
    radius: [dp(30)]
    padding: [dp(20), dp(10), dp(10), dp(10)]
    spacing: dp(10)
    opacity: 0
    on_kv_post:
        Animation(opacity=1, d=1, t="out_quad").start(self)
    BoxButton:
        spacing: dp(5)
        orientation: "vertical"
        MDLabel:
            text: "Best Shoes"
            font_style: "H6"
        MoneyLabel:
            text: "[font=Roboto]₦[/font]20,000.00"
        CardButton:
            text: "Buy Now"
            md_bg_color: app.theme_cls.primary_color
            radius: [dp(7), dp(20), dp(7), dp(20)]
    BoxButton:
        orientation: "vertical"
        radius: root.radius
        on_release:
            snack = Snackbar(text="stop touching me, I will tell my mummy for you", \
            snackbar_x="20dp", snackbar_y="20dp", bg_color=app.theme_cls.primary_color,\
            radius=[dp(10)])
            snack.size_hint_x = (Window.width - (snack.snackbar_x * 2)) / Window.width
            snack.open()
            #app.root.current = "lookout"
        RoundedImage:
            source: f"{image_path}shoes.jpg"
            radius: root.radius
        MDBoxLayout:
            adaptive_height: True
            MDLabel:
                text: f"click to view{icon('touch_app', color='#FF8F00')}"
                markup: True
                size_hint_y: None
                height: self.texture_size[1]
                halign: "center"
<IconCard@MDCard>:
    size_hint: None, None
    size: self.minimum_size
    radius: [dp(30)]
    elevation: 0.2
    callback: lambda x: None
    icon: "heart-outline"

    MDIconButton:
        icon: root.icon
        theme_text_color: "Custom"
        text_color: get_color_from_hex("FF1744")
<IconButton@MDCard>
    radius: dp(30)
    icon: "phone"
    size_hint_y: None
    height: self.minimum_height
    padding: dp(5)
    spacing: dp(10)
    elevation: 10
    text: "call to order"
    MDIconButton:
        icon: root.icon
        theme_text_color: "Custom"
        text_color: app.theme_cls.primary_color
    MDLabel
        text: root.text
        font_style: "Button"



<SetWidget@BoxButton>:
    md_bg_color: app.theme_cls.primary_color
    size_hint_y: None
    height: dp(100)
    spacing: dp(10)
    padding: dp(10)
    text: ""
    icon: ""
    source: ""
    radius: [dp(20)]
    MDIcon:
        source: root.source
        text: root.icon
        markup: True
        size_hint: None, None
        size: dp(50), dp(50)
        pos_hint: {"center_y": .5}
        theme_text_color: "Custom"
        text_color: app.theme_cls.opposite_text_color
    MDLabel:
        text: root.text
        font_style: "H6"
        theme_text_color: "Custom"
        text_color: app.theme_cls.opposite_text_color

<TabBar@MDCard>:
    text: ""
    root: None
    padding: [dp(15), dp(10), dp(15), dp(10)]
    radius: dp(10)
    size_hint: None, None
    height: self.minimum_height
    width: self.minimum_width
    text_color: app.theme_cls.primary_color
    ripple_behavior: True
    on_release:
        self.root.change_screen(self.parent, self)

    MDLabel:
        id: lbl
        text: root.text
        adaptive_size: True
        markup: True
        font_size: dp(18)
        theme_text_color: "Custom"
        text_color: root.text_color

