<TextInput>:
    on_focus: app.on_focus(args[1])
<MDTextField>:
    on_focus: app.on_focus(args[1])
<MDLabel>:
    theme_text_color: "Custom"
    color: get_color_from_hex("#263238")
<ProfilePix@Widget>:
    size_hint: None, None
    size: dp(60), dp(60)
    source: ""
    canvas.before:
        Color:
            rgba: 1,1,1,1
        Ellipse:
            size: self.size
            pos: self.pos
            source: self.source

<Swiper@MDBoxLayout>:
    padding: dp(10)
    orientation: "vertical"
    spacing: dp(10)
    MDBoxLayout:
        adaptive_height: True
        MDLabel:
            text: "Man Shoes"
            font_style: "H5"
            size_hint_y: None
            height: self.texture_size[1]
        MDCard:
            size_hint: None, None
            size: self.minimum_size
            radius: [dp(30)]
            elevation: 0.2
            MDIconButton:
                icon: "heart-outline"
                theme_text_color: "Custom"
                text_color: get_color_from_hex("FF1744")
    MDBoxLayout:
        MDCard:
            elevation: 10
            radius: [dp(10)]
            Image:
                source: f"{image_path}shoe.jpg"
        MDLabel:
            text: f"[font=Roboto]₦[/font]200,000.00"
            halign: "center"
            markup: True
            font_style: "H6"
            size_hint_x:.7
    MDBoxLayout:
        adaptive_height: True
        spacing: dp(10)
        MDCard:
            size_hint_y: None
            height:dp(56)
            md_bg_color: app.theme_cls.primary_color
            radius: [dp(7), dp(20), dp(7), dp(20)]
            ripple_behavior: True
            MDLabel:
                text: "Shop Now"
                halign: "center"
                font_style: "Button"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
        MDCard:
            size_hint_y: None
            height:dp(56)
            md_bg_color: get_color_from_hex("00B8D4")
            radius: [dp(7), dp(20), dp(7), dp(20)]
            ripple_behavior: True
            MDLabel:
                text: "Add To Cart"
                halign: "center"
                font_style: "Button"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
        MDCard:
            size_hint_y: None
            height:dp(56)
            md_bg_color: get_color_from_hex("6200EA")
            radius: [dp(7), dp(20), dp(7), dp(20)]
            ripple_behavior: True
            MDLabel:
                text: "View Product"
                halign: "center"
                font_style: "Button"
                theme_text_color: "Custom"
                text_color: 1,1,1,1

<CarouselLayout>
    adaptive_height: True
    orientation: "vertical"
    Carousel:
        size_hint_y: None
        height: Window.height/3
        pagnitors:[_0, _1, _2, _3]
        on_index:
            root.swipe_pagnitors(*args)
        Swiper:
        Swiper:
        Swiper:
        Swiper
    RelativeLayout:
        size_hint_y:None
        height: dp(50)
        MDBoxLayout:
            adaptive_size: True
            spacing: dp(10)
            pos_hint: {"center_x": .5}
            MDIconButton:
                on_text:
                    print(self.text)
                    self.lbl_txt.markup = True
                    self.lbl_txt.text = icon("chevron_left")
            ItemPagination
                id: _0
            ItemPagination:
                id: _1
                current_index: 1
            ItemPagination:
                id: _2
                current_index: 2
            ItemPagination:
                id: _3
                current_index: 3
            MDIconButton:
                on_text:
                    print(self.text)
                    self.lbl_txt.markup = True
                    self.lbl_txt.text = icon("chevron_right")

<TopInfo@MDBoxLayout>:
    orientation: "vertical"
    MDBoxLayout:
        adaptive_height: True
        padding: dp(10)
        spacing: dp(20)
        MDCard:
            padding: dp(5)
            radius: [dp(10)]
            MDLabel:
                text: "Errand Boy </Ọnye Ozi>"
                font_style: "H4"
                theme_text_color: "Custom"
                text_color: app.theme_cls.primary_color
                size_hint_y: None
                height: self.texture_size[1]
        ProfilePix:
            source: f"{image_path}p.png"
<ItemPagination>
    size_hint: None, None
    size: dp(20), dp(4)
    pos_hint: {'center_y': .5}

    canvas:
        Color:
            rgba:
                self.theme_cls.primary_color\
                if root.current_index == 0 else root.color_round_not_active
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(2)]

