<TextInput>:
    on_focus: app.on_focus(args[1])
<MDTextField>:
    on_focus: app.on_focus(args[1])
<MDLabel>:
    theme_text_color: "Custom"
    color: get_color_from_hex("#263238")
<ProfilePix@ButtonBehavior+Widget>:
    size_hint: None, None
    size: dp(60), dp(60)
    source: ""
    on_release:
        print("hello")
    canvas.before:
        Color:
            rgba: 1,1,1,1
        Ellipse:
            size: self.size
            pos: self.pos
            source: self.source

<CardButton@MDCard>:
    size_hint_y: None
    height:dp(45)
    text: ""
    ripple_behavior: True
    radius: [dp(10)]
    MDLabel:
        text: root.text
        halign: "center"
        font_style: "Button"
        theme_text_color: "Custom"
        text_color: 1,1,1,1

<Swiper@MDBoxLayout>:
    padding: dp(10)
    orientation: "vertical"
    spacing: dp(10)
    MDBoxLayout:
        adaptive_height: True
        MDLabel:
            text: "Man Shoes"
            font_style: "H5"
            size_hint_y: None
            height: self.texture_size[1]
        MDCard:
            size_hint: None, None
            size: self.minimum_size
            radius: [dp(30)]
            elevation: 0.2
            MDIconButton:
                icon: "heart-outline"
                theme_text_color: "Custom"
                text_color: get_color_from_hex("FF1744")
    MDBoxLayout:
        RelativeLayout:
            MDCard:
                elevation: 10
                radius: [dp(10)]
                size_hint_x: None
                width: Window.width/2.3
                pos_hint: {"center_x": .5}
                RoundedImage:
                    source: f"{image_path}shoes.jpg"
                    radius: [dp(10)]
        MDLabel:
            text: f"[font=Roboto]₦[/font]200,000.00"
            halign: "center"
            markup: True
            font_style: "H6"
            size_hint_x:.7
            theme_text_color: "Custom"
            text_color: app.theme_cls.primary_color
    MDBoxLayout:
        adaptive_height: True
        spacing: dp(10)
        CardButton:
            text: "Shop Now"
            md_bg_color: app.theme_cls.primary_color
            radius: [dp(7), dp(20), dp(7), dp(20)]
        CardButton:
            md_bg_color: get_color_from_hex("00B8D4")
            radius: [dp(7), dp(20), dp(7), dp(20)]
            text: "Add To Cart"

        CardButton:
            md_bg_color: get_color_from_hex("6200EA")
            radius: [dp(7), dp(20), dp(7), dp(20)]
            text: "View Product"

<CarouselLayout>
    adaptive_height: True
    orientation: "vertical"
    swipers: []
    Carousel:
        size_hint_y: None
        height: Window.height/2.3
        pagnitors:[_0, _1, _2, _3]
        on_index:
            root.swipe_pagnitors(*args)
        Swiper:
            id: s0
        Swiper:
            id: s1
        Swiper:
            id: s2
        Swiper:
            id: s3
    RelativeLayout:
        size_hint_y:None
        height: dp(10)
        MDBoxLayout:
            adaptive_size: True
            spacing: dp(10)
            pos_hint: {"center_x": .5}
#            MDIconButton:
#                on_text:
#                    self.lbl_txt.markup = True
#                    self.lbl_txt.text = icon("chevron_left")
            ItemPagination
                id: _0
            ItemPagination:
                id: _1
                current_index: 1
            ItemPagination:
                id: _2
                current_index: 2
            ItemPagination:
                id: _3
                current_index: 3
#            MDIconButton:
#                on_text:
#                    self.lbl_txt.markup = True
#                    self.lbl_txt.text = icon("chevron_right")

<TopInfo@MDBoxLayout>:
    orientation: "vertical"
    adaptive_height: True
    MDBoxLayout:
        id: search
        adaptive_height: True
        padding: dp(10)
        spacing: dp(20)
        M_CardTextField:
            elevation: 10
            hint_text: "search"
            icon_right: icon("search")
            radius: dp(20)
            text_field_disabled: True
            icon_right_color: app.theme_cls.primary_color
            icon_left_color: app.theme_cls.primary_color
            foreground_color: [0, 0, 0, 0.8] if app.theme_cls.theme_style == "Light" else [1,1,1,1]
            cursor_color: [0, 0, 0, .7] if app.theme_cls.theme_style == "Light" else [1,1,1,1]
            md_bg_color: [1,1,1,1] if app.theme_cls.theme_style == "Light" else get_color_from_hex("1f1f1f")
            background_color: [1,1,1,1] if app.theme_cls.theme_style == "Light" else get_color_from_hex("1f1f1f")
            disabled_foreground_color: [0.5, 0.5, 0.5, 1.0]
        ProfilePix:
            source: f"{image_path}p.png"
<ItemPagination>
    size_hint: None, None
    size: dp(20), dp(4)
    pos_hint: {'center_y': .5}

    canvas:
        Color:
            rgba:
                self.theme_cls.primary_color\
                if root.current_index == 0 else root.color_round_not_active
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(2)]

<NavButton@Button_Item>:
    icon_color: 1,1,1,1
    text_color: 1,1,1,1
    button_bg_color: app.theme_cls.primary_color
    badge_disabled: True

<BoxButton@ButtonBehavior+MDBoxLayout>

<Products@MDCard>:
    orientation: "vertical"
    radius: [dp(10)]
    size_hint_x: None
    width: Window.width/2.5
    source: ""

    MDBoxLayout:
        adaptive_height: True
        padding: dp(10)
        spacing: dp(5)
        MDCard:
            padding: dp(10)
            radius: [dp(5)]
            MDLabel:
                text:f"[font=Roboto]₦[/font]20,000.00"
                font_style: "H6"
                size_hint_y: None
                height: self.texture_size[1]
                markup: True
                pos_hint:{"center_y": .5}
                theme_text_color: "Custom"
                text_color: app.theme_cls.primary_color
        MDIconButton:
            icon: "heart-outline"
            theme_text_color: "Custom"
            text_color: get_color_from_hex("FF1744")
    BoxButton:
        orientation: "vertical"
        on_release: print("hello")
        RoundedImage:
            id: image
            source: root.source

        MDBoxLayout:
            adaptive_height: True
            orientation: "vertical"
            padding: dp(10)
            spacing: dp(5)
            MDLabel:
                text: "Onye Owa Shoes"
                font_style: "H6"
                size_hint_y: None
                height: self.texture_size[1]
                markup: True
            NocenStore
    MDBoxLayout:
        adaptive_height: True
        padding: dp(10)
        CardButton:
            id: bt
            md_bg_color: app.theme_cls.primary_color
            text: "Add To Cart"
            radius: [dp(20)]
            on_release: print("hello", args)

<NocenStore@MDBoxLayout>:
    adaptive_height: True
    size_hint_x: None
    width: Window.width/3
    md_bg_color: 0,1,0,.1
    pos_hint:{"center_y": .5}
    radius: [dp(5)]
    MDLabel:
        id: la
        text: "NOCENSTORE"
        italic: True
        color: app.theme_cls.primary_color
        size_hint_y: None
        height: self.texture_size[1]
        halign: "center"

<RoundedImage@AsyncImage>:
    radius: [dp(5)]
    canvas.before:
        StencilPush:
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: self.radius if self.radius else [dp(5)]
        StencilUse
    canvas.after:
        StencilUnUse:
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: self.radius if self.radius else [dp(5)]
        StencilPop